spring:
  application:
    name: build-it-with-spring-boot-mvc-jpa-thymeleaf
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:h2:mem:spring_security_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true

logging:
  level:
    root: DEBUG
