spring:
  application:
    name: build-it-with-spring-boot-mvc-jpa-thymeleaf
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:h2:mem:spring_security_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 5025
  thymeleaf:
    cache: false



logging:
  level:
    root: DEBUG
    sun.rmi: INFO
    org.hibernate.type: INFO
    javax.management: INFO
